[package]
name = "omclone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["main_ui"]
#choose one of the following
benchmark = []
main_ui = []
cx_checker = []

[profile.dev]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3

[dependencies]
slotmap = "1.0"
bitflags = "1.3"
nalgebra = "0.30"
num-traits = "0.2"
num-derive = "0.3"
rustc-hash = "1.1"
smallvec = "1.8"

egui = "0.16.0"
miniquad = { version = "=0.3.0-alpha.43" }
egui-miniquad = "0.8.0"
image = "0.24.1"

color-eyre = {version = "0.6", optional = true}
simple-eyre = "0.3"